[theme]
# 基础主题：light 或 dark
base = "light"

# 主色调 - 用于按钮、焦点等交互元素
primaryColor = "#f59e0b"  # 橙色（美食主题）

# 背景色
backgroundColor = "#fdfdf8" 
secondaryBackgroundColor = "#ecebe3" 

# 边框和圆角
baseRadius = "0.5rem"  # 中等圆角
buttonRadius = "0.5rem"  # 按钮圆角
borderColor = "#e5e7eb"  # 浅灰色边框
